### ISSUE TITLE
4.4 LoadMore bug report

### ISSUE THREAD

**Issue by andforce** [Demievil/SwipeRefreshLayout#1]
Can NOT see ProgressBar at bottom , When LoadMore.

**Comment by Demievil** [comment]
Can the item be loaded successfully? You can try changing the style of ProgressBar in XML.

**Comment by ikkyu0319** [comment]
Can NOT see ProgressBar at bottom ， When LoadMore. too~

**Comment by icebergxiaofei** [comment]
Can NOT see ProgressBar at bottom ， When LoadMore. too +1 ~~

**Comment by Demievil** [comment]
ok, I will check it recently :)

**Comment by leegh15** [comment]
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at com.myview.RefreshLayout.dispatchTouchEvent(RefreshLayout.java:53)

**Comment by wangzhuangzhuang** [comment]
我也遇到了这个问题：手指快速的向上滚动屏幕，让listview自己滚动到底部。结果底部显示more而不进行刷新。
这种情况下在dispatchTouchEvent()中，MotionEvent.ACTION_UP时:
(1)调mListView.getLastVisiblePosition()获取到的貌似是滑动前或者离滑动开始时很近的时刻的值（如果用楼主的demo，例如 5 或者 6）。
(2)mListView.getChildAt(mListView.getChildCount() - 1).getBottom()获取到的值貌似也是滑动以前的（2000多）

解决办法：在listview停止滑动的时候，再检测是否滑动到了底部
mListView.setOnScrollListener(new AbsListView.OnScrollListener() {
            @Override
            public void onScrollStateChanged(AbsListView view, int scrollState) {
                switch (scrollState) {
                    case SCROLL_STATE_FLING:
                        break;
                    case SCROLL_STATE_IDLE:
                         //在这里判断是否滚动到了底部
                        if (canLoadMore()) {
                            loadData();
                        }
                        break;
                }
            }

            @Override
            public void onScroll(AbsListView view, int firstVisibleItem, int visibleItemCount, int totalItemCount) {

            }
        });

**Comment by leegh15** [comment]
我的是因为 在先清空list再加载数据，在同时点击的时候就可能会出现数组下标越界
